-- ============================================================
-- ВЕРСИЯ 3
-- Все посетители могут:
-- 1) добавить человека;
-- 2) перенести ЛЮБОГО человека в конец;
-- 3) удалить ЛЮБОГО человека кнопкой "Ответил".
--
-- Выполните ВЕСЬ файл в Supabase -> SQL Editor -> Run.
-- ============================================================

create sequence if not exists public.queue_order_seq;

create table if not exists public.teacher_queue (
  id bigint generated by default as identity primary key,
  surname text not null,
  teacher smallint not null check (teacher in (1, 2)),
  order_key bigint not null default nextval('public.queue_order_seq'),
  created_at timestamptz not null default now(),
  constraint surname_length check (char_length(trim(surname)) between 1 and 60)
);

-- Старый owner_token больше не используется.
alter table public.teacher_queue
  drop column if exists owner_token;

create unique index if not exists teacher_queue_unique_surname
  on public.teacher_queue (teacher, lower(trim(surname)));

create index if not exists teacher_queue_order
  on public.teacher_queue (teacher, order_key, id);

alter table public.teacher_queue enable row level security;

-- Прямой доступ к таблице запрещён; работа только через RPC-функции ниже.
revoke all on table public.teacher_queue from anon, authenticated;
revoke all on sequence public.queue_order_seq from anon, authenticated;

-- Удаляем v3-функции при повторном запуске, затем создаём заново.
drop function if exists public.queue_get_v3();
drop function if exists public.queue_join_v3(text, smallint);
drop function if exists public.queue_move_v3(bigint);
drop function if exists public.queue_done_v3(bigint);

create function public.queue_get_v3()
returns table (
  id bigint,
  surname text,
  teacher smallint,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    q.id,
    q.surname,
    q.teacher,
    q.created_at
  from public.teacher_queue q
  order by q.teacher, q.order_key, q.id;
$$;

create function public.queue_join_v3(
  p_surname text,
  p_teacher smallint
)
returns table (id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_surname text;
  v_id bigint;
begin
  v_surname := trim(p_surname);

  if v_surname is null
     or char_length(v_surname) = 0
     or char_length(v_surname) > 60 then
    raise exception 'invalid_surname';
  end if;

  if p_teacher not in (1, 2) then
    raise exception 'invalid_teacher';
  end if;

  begin
    insert into public.teacher_queue (surname, teacher)
    values (v_surname, p_teacher)
    returning teacher_queue.id into v_id;
  exception
    when unique_violation then
      raise exception 'surname_already_exists';
  end;

  return query select v_id;
end;
$$;

-- НИКАКОЙ проверки владельца. Любой anon-посетитель может вызвать эту функцию.
create function public.queue_move_v3(
  p_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.teacher_queue
  set order_key = nextval('public.queue_order_seq')
  where id = p_id;

  if not found then
    raise exception 'row_not_found';
  end if;
end;
$$;

-- НИКАКОЙ проверки владельца. Любой anon-посетитель может удалить запись.
create function public.queue_done_v3(
  p_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.teacher_queue
  where id = p_id;

  if not found then
    raise exception 'row_not_found';
  end if;
end;
$$;

revoke all on function public.queue_get_v3() from public;
revoke all on function public.queue_join_v3(text, smallint) from public;
revoke all on function public.queue_move_v3(bigint) from public;
revoke all on function public.queue_done_v3(bigint) from public;

grant execute on function public.queue_get_v3() to anon, authenticated;
grant execute on function public.queue_join_v3(text, smallint) to anon, authenticated;
grant execute on function public.queue_move_v3(bigint) to anon, authenticated;
grant execute on function public.queue_done_v3(bigint) to anon, authenticated;

-- Просим PostgREST/Supabase перечитать схему сразу после выполнения SQL.
notify pgrst, 'reload schema';
