-- ============================================================
-- VERSION 4: простая авторизация имя + пароль
-- Пароль хранится только как bcrypt-хэш через pgcrypto.
-- Функции смены пароля НЕТ.
--
-- Новые записи очереди принадлежат конкретному аккаунту.
-- Чужие новые записи нельзя переносить или удалять.
-- Старые записи без владельца может убрать любой вошедший пользователь,
-- чтобы они не зависли после миграции.
--
-- Выполните ВЕСЬ файл в Supabase -> SQL Editor -> Run.
-- ============================================================

create extension if not exists pgcrypto;
create sequence if not exists public.queue_order_seq;

-- Пользователи
create table if not exists public.queue_users (
  id bigint generated by default as identity primary key,
  username text not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists queue_users_username_unique
  on public.queue_users (lower(trim(username)));

-- Сессии
create table if not exists public.queue_sessions (
  token uuid primary key default gen_random_uuid(),
  user_id bigint not null references public.queue_users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists queue_sessions_user_id_idx
  on public.queue_sessions(user_id);

-- Очередь
create table if not exists public.teacher_queue (
  id bigint generated by default as identity primary key,
  surname text not null,
  teacher smallint not null check (teacher in (1, 2)),
  order_key bigint not null default nextval('public.queue_order_seq'),
  created_at timestamptz not null default now()
);

alter table public.teacher_queue
  add column if not exists order_key bigint;

update public.teacher_queue
set order_key = nextval('public.queue_order_seq')
where order_key is null;

alter table public.teacher_queue
  alter column order_key set default nextval('public.queue_order_seq');

alter table public.teacher_queue
  alter column order_key set not null;

-- Владелец записи. NULL = старая запись до авторизации.
alter table public.teacher_queue
  add column if not exists owner_user_id bigint references public.queue_users(id) on delete set null;

create unique index if not exists teacher_queue_unique_surname
  on public.teacher_queue (teacher, lower(trim(surname)));

create index if not exists teacher_queue_order
  on public.teacher_queue (teacher, order_key, id);

-- Прямой доступ к таблицам запрещаем.
alter table public.queue_users enable row level security;
alter table public.queue_sessions enable row level security;
alter table public.teacher_queue enable row level security;

revoke all on table public.queue_users from anon, authenticated;
revoke all on table public.queue_sessions from anon, authenticated;
revoke all on table public.teacher_queue from anon, authenticated;
revoke all on sequence public.queue_order_seq from anon, authenticated;

-- Удаляем v4 функции при повторном запуске.
drop function if exists public.queue_register_v4(text, text);
drop function if exists public.queue_login_v4(text, text);
drop function if exists public.queue_logout_v4(uuid);
drop function if exists public.queue_get_v4(uuid);
drop function if exists public.queue_join_v4(text, smallint, uuid);
drop function if exists public.queue_move_v4(bigint, uuid);
drop function if exists public.queue_done_v4(bigint, uuid);

-- Регистрация. Пароль сразу хэшируется и больше нигде не возвращается.
create function public.queue_register_v4(
  p_username text,
  p_password text
)
returns table (
  session_token uuid,
  username text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
  v_user_id bigint;
  v_token uuid;
begin
  v_username := trim(p_username);

  if v_username is null or char_length(v_username) < 2 or char_length(v_username) > 40 then
    raise exception 'invalid_username';
  end if;

  if p_password is null or char_length(p_password) < 4 or char_length(p_password) > 100 then
    raise exception 'invalid_password';
  end if;

  begin
    insert into public.queue_users(username, password_hash)
    values (v_username, crypt(p_password, gen_salt('bf')))
    returning id into v_user_id;
  exception
    when unique_violation then
      raise exception 'username_taken';
  end;

  insert into public.queue_sessions(user_id)
  values (v_user_id)
  returning token into v_token;

  return query select v_token, v_username;
end;
$$;

-- Вход
create function public.queue_login_v4(
  p_username text,
  p_password text
)
returns table (
  session_token uuid,
  username text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.queue_users%rowtype;
  v_token uuid;
begin
  select *
  into v_user
  from public.queue_users
  where lower(trim(username)) = lower(trim(p_username))
    and password_hash = crypt(p_password, password_hash)
  limit 1;

  if v_user.id is null then
    raise exception 'invalid_credentials';
  end if;

  insert into public.queue_sessions(user_id)
  values (v_user.id)
  returning token into v_token;

  return query select v_token, v_user.username;
end;
$$;

-- Выход
create function public.queue_logout_v4(
  p_session_token uuid
)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.queue_sessions
  where token = p_session_token;
$$;

-- Просмотр очереди.
-- is_own позволяет интерфейсу показать кнопки только у своих записей.
create function public.queue_get_v4(
  p_session_token uuid default null
)
returns table (
  id bigint,
  surname text,
  teacher smallint,
  created_at timestamptz,
  owner_username text,
  is_own boolean
)
language sql
security definer
set search_path = public
as $$
  select
    q.id,
    q.surname,
    q.teacher,
    q.created_at,
    u.username as owner_username,
    (
      s.user_id is not null
      and q.owner_user_id = s.user_id
    ) as is_own
  from public.teacher_queue q
  left join public.queue_users u on u.id = q.owner_user_id
  left join public.queue_sessions s
    on s.token = p_session_token
  order by q.teacher, q.order_key, q.id;
$$;

-- Добавление записи только после входа.
create function public.queue_join_v4(
  p_surname text,
  p_teacher smallint,
  p_session_token uuid
)
returns table (id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_surname text;
  v_id bigint;
begin
  select user_id into v_user_id
  from public.queue_sessions
  where token = p_session_token;

  if v_user_id is null then
    raise exception 'invalid_session';
  end if;

  v_surname := trim(p_surname);

  if v_surname is null or char_length(v_surname) = 0 or char_length(v_surname) > 60 then
    raise exception 'invalid_surname';
  end if;

  if p_teacher not in (1, 2) then
    raise exception 'invalid_teacher';
  end if;

  begin
    insert into public.teacher_queue(surname, teacher, order_key, owner_user_id)
    values (v_surname, p_teacher, nextval('public.queue_order_seq'), v_user_id)
    returning teacher_queue.id into v_id;
  exception
    when unique_violation then
      raise exception 'surname_already_exists';
  end;

  return query select v_id;
end;
$$;

-- Перенос: только владелец записи.
-- Исключение: legacy-запись с owner_user_id IS NULL может быть обработана любым вошедшим.
create function public.queue_move_v4(
  p_id bigint,
  p_session_token uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_owner_user_id bigint;
begin
  select user_id into v_user_id
  from public.queue_sessions
  where token = p_session_token;

  if v_user_id is null then
    raise exception 'invalid_session';
  end if;

  select owner_user_id into v_owner_user_id
  from public.teacher_queue
  where id = p_id;

  if not found then
    raise exception 'row_not_found';
  end if;

  if v_owner_user_id is not null and v_owner_user_id <> v_user_id then
    raise exception 'not_owner';
  end if;

  update public.teacher_queue
  set order_key = nextval('public.queue_order_seq')
  where id = p_id;
end;
$$;

-- Удаление: только владелец записи.
-- Legacy-записи может удалить любой вошедший.
create function public.queue_done_v4(
  p_id bigint,
  p_session_token uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_owner_user_id bigint;
begin
  select user_id into v_user_id
  from public.queue_sessions
  where token = p_session_token;

  if v_user_id is null then
    raise exception 'invalid_session';
  end if;

  select owner_user_id into v_owner_user_id
  from public.teacher_queue
  where id = p_id;

  if not found then
    raise exception 'row_not_found';
  end if;

  if v_owner_user_id is not null and v_owner_user_id <> v_user_id then
    raise exception 'not_owner';
  end if;

  delete from public.teacher_queue
  where id = p_id;
end;
$$;

-- Разрешаем браузеру только RPC.
revoke all on function public.queue_register_v4(text, text) from public;
revoke all on function public.queue_login_v4(text, text) from public;
revoke all on function public.queue_logout_v4(uuid) from public;
revoke all on function public.queue_get_v4(uuid) from public;
revoke all on function public.queue_join_v4(text, smallint, uuid) from public;
revoke all on function public.queue_move_v4(bigint, uuid) from public;
revoke all on function public.queue_done_v4(bigint, uuid) from public;

grant execute on function public.queue_register_v4(text, text) to anon, authenticated;
grant execute on function public.queue_login_v4(text, text) to anon, authenticated;
grant execute on function public.queue_logout_v4(uuid) to anon, authenticated;
grant execute on function public.queue_get_v4(uuid) to anon, authenticated;
grant execute on function public.queue_join_v4(text, smallint, uuid) to anon, authenticated;
grant execute on function public.queue_move_v4(bigint, uuid) to anon, authenticated;
grant execute on function public.queue_done_v4(bigint, uuid) to anon, authenticated;

notify pgrst, 'reload schema';
