-- ============================================================
-- Онлайн-очередь: настройка Supabase
-- Выполните ВЕСЬ этот файл в Supabase -> SQL Editor -> Run.
-- ============================================================

-- Для генерации UUID обычно расширение уже включено в Supabase.
create extension if not exists pgcrypto;

-- Порядок очереди. nextval() безопасно выдаёт уникальное растущее значение.
create sequence if not exists public.queue_order_seq;

create table if not exists public.teacher_queue (
  id bigint generated by default as identity primary key,
  surname text not null,
  teacher smallint not null check (teacher in (1, 2)),
  owner_token uuid not null,
  order_key bigint not null default nextval('public.queue_order_seq'),
  created_at timestamptz not null default now(),

  constraint surname_length check (char_length(trim(surname)) between 1 and 60)
);

-- Одна и та же фамилия не может дважды стоять к одному преподавателю.
create unique index if not exists teacher_queue_unique_surname
  on public.teacher_queue (teacher, lower(trim(surname)));

create index if not exists teacher_queue_order
  on public.teacher_queue (teacher, order_key, id);

-- Запрещаем прямой доступ к таблице из браузера.
alter table public.teacher_queue enable row level security;

revoke all on table public.teacher_queue from anon, authenticated;
revoke all on sequence public.queue_order_seq from anon, authenticated;

-- На всякий случай удаляем старые функции с такими именами,
-- чтобы повторный запуск файла не мешал настройке.
drop function if exists public.get_queue();
drop function if exists public.join_queue(text, smallint, uuid);
drop function if exists public.move_to_end(bigint, uuid);
drop function if exists public.mark_done(bigint, uuid);

-- ------------------------------------------------------------
-- Получить очередь.
-- owner_token наружу НЕ возвращается.
-- ------------------------------------------------------------
create function public.get_queue()
returns table (
  id bigint,
  surname text,
  teacher smallint,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    q.id,
    q.surname,
    q.teacher,
    q.created_at
  from public.teacher_queue q
  order by q.teacher, q.order_key, q.id;
$$;

-- ------------------------------------------------------------
-- Встать в очередь.
-- ------------------------------------------------------------
create function public.join_queue(
  p_surname text,
  p_teacher smallint,
  p_owner_token uuid
)
returns table (id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_surname text;
  v_id bigint;
begin
  v_surname := trim(p_surname);

  if v_surname is null or char_length(v_surname) = 0 or char_length(v_surname) > 60 then
    raise exception 'invalid_surname';
  end if;

  if p_teacher not in (1, 2) then
    raise exception 'invalid_teacher';
  end if;

  if p_owner_token is null then
    raise exception 'invalid_owner_token';
  end if;

  begin
    insert into public.teacher_queue (surname, teacher, owner_token)
    values (v_surname, p_teacher, p_owner_token)
    returning teacher_queue.id into v_id;
  exception
    when unique_violation then
      raise exception 'surname_already_exists';
  end;

  return query select v_id;
end;
$$;

-- ------------------------------------------------------------
-- Перенести СВОЮ запись в конец.
-- ------------------------------------------------------------
create function public.move_to_end(
  p_id bigint,
  p_owner_token uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.teacher_queue
  set order_key = nextval('public.queue_order_seq')
  where id = p_id
    and owner_token = p_owner_token;

  if not found then
    raise exception 'not_owner';
  end if;
end;
$$;

-- ------------------------------------------------------------
-- Отметить СВОЮ запись как "Ответил" и удалить из очереди.
-- ------------------------------------------------------------
create function public.mark_done(
  p_id bigint,
  p_owner_token uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.teacher_queue
  where id = p_id
    and owner_token = p_owner_token;

  if not found then
    raise exception 'not_owner';
  end if;
end;
$$;

-- Запрещаем выполнение всем по умолчанию и выдаём только нужные RPC.
revoke all on function public.get_queue() from public;
revoke all on function public.join_queue(text, smallint, uuid) from public;
revoke all on function public.move_to_end(bigint, uuid) from public;
revoke all on function public.mark_done(bigint, uuid) from public;

grant execute on function public.get_queue() to anon, authenticated;
grant execute on function public.join_queue(text, smallint, uuid) to anon, authenticated;
grant execute on function public.move_to_end(bigint, uuid) to anon, authenticated;
grant execute on function public.mark_done(bigint, uuid) to anon, authenticated;

-- Готово.
-- После выполнения SQL откройте config.js и вставьте:
-- 1) SUPABASE_URL
-- 2) Publishable key / anon key
